"""Signatures for public QR profile links, and for the Paystack webhook.

**What the QR signature proves, and what it does not.** The signature is
deterministic for a given KUID and printed on a card that anybody can photograph.
So a valid signature proves *this link was generated by KAFRIADA* — it does not
prove the bearer is the person on the screen, and it does not survive being
photocopied. The public profile must therefore say "Issued by KAFRIADA — check the
photo matches the bearer", never "verified athlete". Wording is part of the
security control here, not decoration.

**Why the version prefix exists.** Signatures look like ``1.a1b2c3d4e5f60718``.
Without that leading key version, rotating ``QR_SECRET`` would invalidate every
card ever printed in Jigawa on the same day. With it, old cards keep verifying
against the retired key while new cards are issued under the new one. Two
characters now; impossible to retrofit once cards are in people's pockets.
"""

from __future__ import annotations

import hashlib
import hmac
import re
from collections.abc import Mapping
from dataclasses import dataclass

from kafriada.settings import Settings, get_settings

# 16 hex characters = 64 bits. This is a tamper check on a public identifier, not
# a confidentiality boundary: an attacker gains nothing by forging a link to a
# profile that is already public. 64 bits makes blind forgery pointless while
# keeping the printed URL short enough to scan reliably on a cheap camera.
SIGNATURE_HEX_LENGTH = 16

_SIGNATURE_RE = re.compile(r"^(?P<version>[1-9][0-9]{0,1})\.(?P<digest>[0-9a-f]{16})$")


@dataclass(frozen=True, slots=True)
class SignatureCheck:
    valid: bool
    key_version: int | None = None
    # True when the signature verified against a retired key. The profile still
    # shows as issued by us, but a re-issue of that card can be scheduled.
    retired_key: bool = False


class QrSigner:
    """Signs and verifies public profile links.

    ``keys`` maps a key version to its secret. Rotation is: add the new version,
    point ``current_version`` at it, keep the old entry until every card printed
    under it has been replaced, then delete the entry.
    """

    def __init__(self, keys: Mapping[int, str], current_version: int) -> None:
        if current_version not in keys:
            raise ValueError(f"no secret for current key version {current_version}")
        self._keys = dict(keys)
        self._current = current_version

    def sign(self, kuid: str) -> str:
        """Return ``{version}.{16 hex}`` for the current key."""
        digest = self._digest(kuid, self._keys[self._current])
        return f"{self._current}.{digest}"

    def verify(self, kuid: str, signature: str | None) -> SignatureCheck:
        """Check a signature. Never raises — an absent or malformed signature is
        an ordinary case, because people type KUIDs by hand and photocopy cards.
        """
        if not signature:
            return SignatureCheck(valid=False)

        match = _SIGNATURE_RE.match(signature)
        if match is None:
            return SignatureCheck(valid=False)

        version = int(match.group("version"))
        secret = self._keys.get(version)
        if secret is None:
            return SignatureCheck(valid=False)

        expected = self._digest(kuid, secret)
        if not hmac.compare_digest(expected, match.group("digest")):
            return SignatureCheck(valid=False)

        return SignatureCheck(
            valid=True, key_version=version, retired_key=version != self._current
        )

    @staticmethod
    def _digest(kuid: str, secret: str) -> str:
        mac = hmac.new(secret.encode("utf-8"), kuid.encode("utf-8"), hashlib.sha256)
        return mac.hexdigest()[:SIGNATURE_HEX_LENGTH]


def build_qr_signer(settings: Settings | None = None) -> QrSigner:
    cfg = settings or get_settings()
    # Retired keys are added here when QR_SECRET is rotated. Keeping the map in
    # code rather than in the environment makes the rotation an auditable commit.
    keys = {cfg.qr_key_version: cfg.qr_secret.get_secret_value()}
    return QrSigner(keys, cfg.qr_key_version)


# ---------------------------------------------------------------------------
# Paystack webhook
# ---------------------------------------------------------------------------
def verify_paystack_signature(*, raw_body: bytes, header_signature: str | None,
                              secret_key: str) -> bool:
    """Verify the ``x-paystack-signature`` header against the raw request body.

    ``raw_body`` must be the exact bytes Paystack sent. Parsing the JSON and
    re-serialising it changes key order and whitespace, and the HMAC then never
    matches — a failure that looks like "Paystack is sending bad signatures" and
    costs a day to find. Read the body with ``await request.body()`` *before*
    anything touches it, verify, and only then parse.

    This is also why the webhook route is exempt from CSRF: it carries no session
    cookie and no CSRF token, because it is a server-to-server call authenticated
    by this HMAC — which is a stronger proof of origin than a cookie ever is.
    """
    if not header_signature:
        return False
    expected = hmac.new(
        secret_key.encode("utf-8"), raw_body, hashlib.sha512
    ).hexdigest()
    return hmac.compare_digest(expected, header_signature.strip().lower())
