"""Write the logo SVG set and a React component from logo-trace.json."""
import json, os, sys

TRACE, WEB = sys.argv[1], sys.argv[2]
t = json.load(open(TRACE))
P, B = t["paths"], t["boxes"]
GREEN, RED, BLACK, WHITE = "#0EAD2C", "#EB0002", "#0A0F0B", "#FFFFFF"
PAD = 6


def box(*names):
    bs = [B[n] for n in names]
    x0 = min(b[0] for b in bs) - PAD; y0 = min(b[1] for b in bs) - PAD
    x1 = max(b[2] for b in bs) + PAD; y1 = max(b[3] for b in bs) + PAD
    return x0, y0, x1 - x0, y1 - y0


def svg(parts, vb, title):
    x, y, w, h = vb
    body = "".join(f'<path fill="{c}" d="{d}"/>' for c, d in parts)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x} {y} {w} {h}" '
            f'role="img" aria-label="{title}"><title>{title}</title>{body}</svg>\n')


def figure(g, r, k):
    return [(k, P["fig_black"]), (r, P["fig_red"]), (g, P["fig_green"])]


VARIANTS = {
    "full": (["figure", "name", "tag"], lambda g, r, k: figure(g, r, k) + [(k, P["name"]), (k, P["tag"])]),
    "horizontal": (["figure", "name"], lambda g, r, k: figure(g, r, k) + [(k, P["name"])]),
    "mark": (["figure"], figure),
    "wordmark": (["name"], lambda g, r, k: [(k, P["name"])]),
}
SCHEMES = {"": (GREEN, RED, BLACK), "-white": (WHITE,) * 3, "-black": (BLACK,) * 3}
SCHEMES_ON_DARK = {"-on-dark": (GREEN, RED, WHITE)}

out = os.path.join(WEB, "public", "brand")
os.makedirs(out, exist_ok=True)
for name, (boxes, build) in VARIANTS.items():
    for suffix, cols in {**SCHEMES, **SCHEMES_ON_DARK}.items():
        path = os.path.join(out, f"kafriada-net-{name}{suffix}.svg")
        open(path, "w", newline="\n").write(svg(build(*cols), box(*boxes), "KAFRIADA NET"))

# React component: horizontal lockup and mark, the dark parts follow currentColor.
hx = box("figure", "name"); mx = box("figure")
tsx = f'''// Generated by scripts/design/build_logo.py from the traced logo. Do not edit by hand.

const FIG_BLACK = "{P["fig_black"]}";
const FIG_RED = "{P["fig_red"]}";
const FIG_GREEN = "{P["fig_green"]}";
const NAME = "{P["name"]}";

/** The figure's dark body and the wordmark use currentColor, so they follow the theme. */
export function Figure() {{
  return (
    <>
      <path fill="currentColor" d={{FIG_BLACK}} />
      <path fill="var(--kit-red)" d={{FIG_RED}} />
      <path fill="var(--pitch)" d={{FIG_GREEN}} />
    </>
  );
}}

export function Logo({{ variant = "horizontal", className }}: {{ variant?: "horizontal" | "mark"; className?: string }}) {{
  if (variant === "mark") {{
    return (
      <svg viewBox="{mx[0]} {mx[1]} {mx[2]} {mx[3]}" role="img" aria-label="KAFRIADA NET" className={{className}}>
        <Figure />
      </svg>
    );
  }}
  return (
    <svg viewBox="{hx[0]} {hx[1]} {hx[2]} {hx[3]}" role="img" aria-label="KAFRIADA NET" className={{className}}>
      <Figure />
      <path fill="currentColor" d={{NAME}} />
    </svg>
  );
}}
'''
open(os.path.join(WEB, "src", "components", "brand", "Logo.tsx"), "w", newline="\n").write(tsx) if os.path.isdir(os.path.join(WEB, "src", "components", "brand")) else None
print(sorted(os.listdir(out)), hx, mx)
